# Generated by Django 4.1.1 on 2022-09-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20190210_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qlevel',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
