# Generated by Django 4.1.1 on 2022-09-24 09:57

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_qlevel_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='detail',
            field=markdownfield.models.MarkdownField(default='NA', rendered_field='text_rendered'),
        ),
    ]
