# Generated by Django 4.1.1 on 2022-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=models.TextField(),
        ),
    ]
