# Generated by Django 4.2.4 on 2023-09-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_stud_user_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='time_diff',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
