# Generated by Django 4.2.4 on 2023-09-03 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_stud_time_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='user_self',
        ),
        migrations.AddField(
            model_name='stud',
            name='time_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
