# Generated by Django 4.2.4 on 2023-09-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_stud_user_self_stud_time_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='time',
        ),
    ]
