# Generated by Django 4.2.4 on 2023-09-03 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_stud_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='time_diff',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
