# Generated by Django 4.2.4 on 2023-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_stud_time_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='time_diff',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
